### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by BrackoNe** [BjornRasmussen/Lanes#5]
Hi,

I have found your plugin, and it seems to have a really good perspective in the future.
Do you have any video tutorials or at least a written one? How can we use this plugin?
I can only toggle the "Activate lane editing mode" button, the plugin switches the map style, but not sure how to edit it. I can only pan the map with the right-click, and once I switch to select mode (by pressing "S" button), it disables the plugin, and that's it...

Thanks,
Nemanja

**Comment by BjornRasmussen** [comment]
The current version doesn't have editing yet, but I'm in the process of adding it.  
Clicking on a road will open a pop-up that will allow you to change the number of lanes and the types of lanes.  
Intersections between roads will have a way to drag input lanes into output lanes to specify lane connectivity, which will be stored in connectivity relations.
I'm also hoping to eventually add a way to adjust road alignments (move child nodes) without leaving the lane mode.

I decided to release the beta version since I'd mostly finished the rendering, which might be useful to some people.

If you have any suggestions for other ways the plugin could work, please let me know!

**Comment by BrackoNe** [comment]
Not getting any pop-ups. Maybe that's the reason why I have sent the initial message a few days ago. :)
I have tried on both official and nightly builds of the JOSM.

**Comment by BjornRasmussen** [comment]
I've got popups in my local version working perfectly now, but I haven't programmed the buttons to work yet.  I think I'll have the basic editing functionally published by new years.

**Comment by BjornRasmussen** [comment]
I added the editing functionality and published a new version.  To try it out, go to the plugin settings in JOSM and update it to the latest version.

**Comment by BrackoNe** [comment]
Now it works! Thanks for the update!
